StyleGuide/Collections.md, StyleGuide/Documents.md
Some notes on collections. This is my understanding of our stance, but we really haven't discussed it, so have at it :).
=> Collections and Document Ids

StyleGuide/Index.md, StyleGuide/Interfaces.md
Slack discussion: https://octopusdeploy.slack.com/archives/CTZT49JFJ/p1590559880133100
=> Pre-amble and Interfaces

Decisions/readme.md, Decisions/template.md
This PR introduces a template for lightweight [Architecture Decision Records](https://www.thoughtworks.com/radar/techniques/lightweight-architecture-decision-records) to help us record the why, when, how, and who of important architectural decisions we make at Octopus for posterity.
=> Architecture Decision Record Template

OctopusServer/ApiVersioning.md
There are plenty of existing clients with hardcoded urls out there. This PR introduces a proposal re how to handle them.
Examples:
* https://github.com/OctopusSamples/SpaceCloner/blob/master/src/DataAccess/OctopusRepository.ps1#L93
* https://github.com/OctopusDeploy/go-octopusdeploy/blob/master/octopusdeploy/tenant.go#L123
=> How to handle existing clients

Decisions/20200716-ClientDesignPrinciples.md, Decisions/readme.md
I decided to replace `Revisions` section with `Data Sources` section.  I think that the vast majority of ADR consumers want to know what the current decision is. 
There will be a much smaller group of people who want to gain a deeper understanding of why the decision was made the way it was. `Options & Considerations` and `Data Sources` sections should be able to provide that detailed information.
=> Design Principles For Octopus Server Clients

Decisions/20200803-EnvelopeResources.md
When deciding on the Config as Code API surface, the concept of Envelope Resources was introduced to allow modelling commits for version controlled reources.
This ADR promotes that specific decision to general purpose guidance for modelling domain interactions.
=> ADR: Envelope Resources

Decisions/20200825-DomainModel.md
**Readable Version:** https://github.com/OctopusDeploy/Architecture/blob/adr-domain-model/Decisions/20200825-DomainModel.md
**Timeline:** Aiming to have concensus on the approaches presented by end of sharpening (Friday 28 Aug).
This PR builds on work completed by @johnsimons, @andyinaus and I that gives us the ability to use ASP.NET Core controllers, and move away from our legacy Nancy infrastructure. Nancy is no longer actively maintained, so this is a desirable direction for Octopus Server to take.
Instead of looking to replicate what we have in "the new world" of ASP.NET, we want to take the time to re-think some of our core architectural approaches before we start creating or migrating new endpoints in earnest.
What this PR presents is a new approach to modelling our core domain, …
=> Domain Modelling in Octopus Server

OctopusServer/Migrations.md
It's not clear when we need to write migration scripts. This is a source of confusing bugs given the pitfalls involved.
This document hopes to make it easy to make a decision.
Feel free to edit/suggest.
=> Add guidelines for writing migration scripts

Octopus Server/FileCache.md, Octopus Server/Job.md, Octopus Server/Retention/ReleaseRetention.md, Octopus Server/Retention/TargetRetention.md, Octopus Server/Retention/index.md
This describes how Tentacle and Release retention currently work.
=> Retention documentation

StructuredConfigurationVariables/StructuredConfigVariables.md
This PR captures a change in behaviour for structured configuration variables.
This fix for [this issue](https://github.com/OctopusDeploy/Issues/issues/6683) made in [this Calamari PR](https://github.com/OctopusDeploy/Calamari/pull/696) resulted in a change in the algorithm we use to determine the parser we use for a file.
The key motivation for this change was a number of customers complaining that they couldn't use this feature because their files didn't use the supported extensions. A common use case was `.config` files (e.g. `web.config`).
Trello card: https://trello.com/c/tM8IgFID/4036-structured-configuration-replacement-will-only-replace-into-xml-files-ending-in-xml
=> Updated docs for Structured Configuration Variables

OctopusServer/ConfigAsCode/NamesOrIds.md
=> Added some more advantages to Current Approach

OctopusServer/ConfigAsCode/NamesOrIds.md
[Readable version](https://github.com/OctopusDeploy/Architecture/blob/mark/cac/nameorids/OctopusServer/ConfigAsCode/NamesOrIds.md)
This cycle, we had a chance to review our current approach to name/ids with a fresh perspective. We had some new eyes on the approach, previous questions being re-raised and some joint concerns have been raised. The most notable concern is: How far the current approach is spreading. But also, there’s concerns around the user-experience for consumers when we deliver this feature.
This document is an attempt to capture all of this information to make sure we’re still heading in the right direction.
=> Name and Id Considerations

OctopusServer/ConfigAsCode/Authentication.md
There have been numerous discussions over the last few cycles on supported authentication methods for Configuration as Code:
* _Do we support Anonymous/SSH/Token based authentication?_
* _Why do we club Password and Tokens in the same field?_
* _Should we code to the long term product strategy for Auth?_
This addition to the Architecture repo aims to document some of these disucssions.
=> Configuration as Code: Authentication

OctopusServer/Steps/StepUI.md
I was trying to strike the right balance that would give readers the important information they need to know in a succinct, easily digestible form, the important reasons why we went in this direction, avoiding the finer details, and giving the right breadcrumbs so that readers can find more information if they need to :spelunk:. 
It feels quite light on details, and I let the diagram do much of the talking. 
Did I strike the right balance?
=> Document the decision to go with a custom step ui framework

OctopusServer/ConfigAsCode/StepTemplates.md
Describes the changes to how Action Templates (a.k.a Step Templates) are serialised to the database and version control, and how we want to approach this problem in the future.
=> Step Templates Documentation

OctopusServer/ConfigAsCode/StepTemplates.md
Updated Step Template documentation given the recent changes introduced in https://github.com/OctopusDeploy/OctopusDeploy/pull/8213
=> Update Step Template documentation

OctopusServer/Api/AspNet.md
Updates to reflect decisions made during Anchovy and Barracuda cycles. Information about builders has been added [here](https://github.com/OctopusDeploy/OctopusDeploy/pull/8838).
=> Anchovy and Barracuda decisions

OctopusServer/Persistence.md
This PR adds a write-up of our position on persistence within the Octopus Server codebase.
=> Add document on persistence.

Steps/Components/StepUI-OptionalValues.md
This PR presents a way we might model optional and required values in the inputs of our step packages.
View the rendered page: https://github.com/OctopusDeploy/Architecture/blob/step-ui/optional-values/Steps/Components/StepUI-OptionalValues.md
=> Added a proposal for optional/required types

OctopusServer/Observability/Logging.md
=> Initial draft of logging document for Octopus Server

OctopusServer/TogglingFeatures.md
Documents available options for toggling Feature availability, the intent of each, and how you would choose the right option for your situation.
Spawned from [🔒 Slack Discussion](https://octopusdeploy.slack.com/archives/CDANN5QLT/p1637727878212900) (internal)
=> Server > Toggling Feature Availability
